### PR TITLE
Add IdeaPlugin support

### PR DESCRIPTION
**Pull request by renatoaraujoc**
Will add a generatedSourceDir if the IdeaPlugin is detected.

### CODE REVIEW

**Comment by griffio** [comment]
@renatoaraujoc,
 
Before you get any further with this PR, I mention that we don't make use of this IdeaPlugin internally in the ewerk plugins.  Typically, it has to be used when trying to add generated sources under the projectDir/build location, IntelliJ cannot set it as a source folder automatically.

We would recommend that generated source be under some other top level "/src/generated" or "/generated/foo" folder, so that Intellij will automatically mark it as source.

**Comment by holgerstolzenberg** [comment]
Hey @renatoaraujoc 

At first thanks for your work. But I am really not sure if I want an IntelliJ dependency in our plugins.

I´ll review the change and come back.

Maybe next time, let´s just have a short discussion with @griffio so we can figure out what is the best for the plugins.

**Comment by renatoaraujoc** [comment]
Hello @griffio and @holgerstolzenberg,

I understand. Well, since this plugin is available to the public, I thought that maybe adding an Idea/Eclipse support would be welcome for those who use these IDEs.
In the end, it's just a matter of plugin detection as you can see in my PR as it shouldn't break the main functionality.

I've cloned your project and tested it myself, the IntelliJ IDEA recognizes the target source dir as a generatedSourceDir and everything works fine for me here.

Again, thank you :)

Renato

**Comment by holgerstolzenberg** [comment]
I am really torn about that.

If we add Idea support, we should at least add Eclipse support for the others out there. Additionally, if we do so, we should add that to all the plugins, also flagging test source directories accordingly.

@griffio What do you think

@renatoaraujoc BTW: The PR can´t be merged because of a Travis build failure

**Comment by griffio** [comment]
@holgerstolzenberg 

At the moment, there are only a couple of reasons to support idea detection, for example the IdeaPlugin, that I know of:-

1. User adds generated source to projectDir/build  (Android Studio supports this config automatically)
2. Working around "bugs" in latest Intellij where it doesn't set the src or test directory

I would prefer to get another couple of cases where people need extra Idea config.

**Pull request closed without merging**
